name: pointvs
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - attrs=22.1.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - commonmark=0.9.1
  - cryptography=38.0.1
  - curl=7.86.0
  - cycler=0.11.0
  - dataclasses=0.8
  - docker-pycreds=0.4.0
  - fastparquet=0.5.0
  - ffmpeg=4.3
  - fftw=3.3.9
  - flit-core=3.6.0
  - fontconfig=2.13.94
  - fonttools=4.25.0
  - freetype=2.12.1
  - future=0.18.2
  - gettext=0.21.0
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.29
  - glew=2.1.0
  - glib=2.69.1
  - glm=0.9.9.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=58.2
  - idna=3.4
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm11=11.1.0
  - libllvm12=12.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.15.8
  - libssh2=1.10.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.8.0
  - llvm-openmp=14.0.6
  - llvmlite=0.39.1
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - nspr=4.35
  - nss=3.74
  - numba=0.56.3
  - numexpr=2.8.4
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openbabel=3.1.1
  - openh264=2.1.1
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.5.1
  - pathtools=0.1.2
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.38.0
  - pluggy=1.0.0
  - ply=3.11
  - pmw=2.0.1
  - promise=2.3
  - protobuf=3.15.8
  - psutil=5.9.0
  - py=1.11.0
  - pycparser=2.21
  - pyg=2.2.0
  - pygments=2.11.2
  - pymol-open-source=2.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - pytest=7.1.2
  - python=3.9.15
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.13.0
  - pytorch-cluster=1.6.0
  - pytorch-scatter=2.1.0
  - python-snappy=0.6.1
  - pytorch-sparse=0.6.15
  - pytz=2022.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - rich=12.5.1
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - sentry-sdk=1.11.1
  - setproctitle=1.3.2
  - setuptools=65.5.0
  - shortuuid=1.0.11
  - sip=6.6.2
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.9
  - sqlite=3.40.0
  - tbb=2021.6.0
  - threadpoolctl=2.2.0
  - thrift=0.17.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - tornado=6.2
  - tqdm=4.64.1
  - typing_extensions=4.4.0
  - tzdata=2022f
  - urllib3=1.26.12
  - wandb=0.13.5
  - wheel=0.37.1
  - xz=5.2.8
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - egnn-pytorch==0.2.6
    - "--editable=git+ssh://git@github.com/jscant/plip.git#egg=plip"
    - rdkit-pypi==2022.9.2
