name: pointvs
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cryptography=38.0.1
  - curl=7.86.0
  - cycler=0.11.0
  - docker-pycreds=0.4.0
  - fastparquet=0.5.0
  - ffmpeg=4.2.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.29
  - glew=2.1.0
  - glib=2.69.1
  - glm=0.9.9.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=68.1
  - idna=3.4
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libidn2=2.3.1
  - libllvm11=11.1.0
  - libllvm12=12.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libopenblas=0.3.21
  - libopus=1.3
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.21.9
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libvpx=1.10.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.3
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - nspr=4.35
  - nss=3.78
  - numexpr=2.8.4
  - numpy-base=1.21.5
  - openh264=1.8.0
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.5.1
  - pathtools=0.1.2
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2.2
  - ply=3.11
  - pmw=2.0.1
  - promise=2.3
  - protobuf=4.21.9
  - psutil=5.9.4
  - pycparser=2.21
  - pymol-open-source=2.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-snappy=0.6.1
  - python_abi=3.9
  - pytorch=1.13.0
  - pytz=2022.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - rich=12.6.0
  - scipy=1.7.3
  - sentry-sdk=1.11.1
  - setproctitle=1.3.2
  - setuptools=65.5.0
  - shortuuid=1.0.11
  - sip=6.6.2
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.9
  - sqlite=3.40.0
  - tbb=2021.5.0
  - thrift=0.17.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - tornado=6.2
  - typing_extensions=4.3.0
  - tzdata=2022f
  - urllib3=1.26.12
  - wandb=0.13.5
  - wheel=0.37.1
  - x264=1!152.20180806
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - "--editable=git+https://github.com/rusty1s/pytorch_sparse.git@bfdca11e4c5e6483066ff744a5bbf56ddf6cec50#egg=torch_sparse"
    - egnn-pytorch==0.2.6
    - einops==0.6.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - llvmlite==0.39.1
    - lxml==4.9.1
    - markupsafe==2.1.1
    - numba==0.56.4
    - numpy==1.22.4
    - plip==2.2.2
    - rdkit-pypi==2022.9.2
    - scikit-learn==1.1.3
    - threadpoolctl==3.1.0
    - torch-cluster==1.6.0
    - torch-geometric==2.2.0
    - torch-scatter==2.1.0
    - torch-spline-conv==1.2.1
    - tqdm==4.64.1
    - "--editable=git+ssh://git@github.com/jscant/plip.git#egg=plip"
