name: unit-tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install SHH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run:  git clone -q 'ssh://git@@github.com/oxcsml/lie-transformer.git'
      - run: conda env create -f environment.yml python=3.8
      - run: conda activate pointvs
      - run: pip install -e .
      - run: pytest -v